export const FETCH_COLORAPI_REQUEST = "FETCH_COLORAPI_REQUEST";
export const FETCH_CONTINUOUSLY = "FETCH_CONTINUOUSLY";
export const FETCH_CANCELED = "FETCH_CANCELED";
export const FETCH_COLORAPI_SUCCESS = "FETCH_COLORAPI_SUCCESS";
